# Generated by Django 6.0.5 on 2026-05-07 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('servico_oferecido', models.CharField(choices=[('corte', 'Corte de Cabelo'), ('barba', 'Barba'), ('corte_barba', 'Corte de Cabelo + Barba'), ('outro', 'Outro')], default='corte', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barbeiro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
